# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MagicCarpet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MagicCarpet
  pod 'AppAuth', '>= 0.91'

  target 'MagicCarpet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MagicCarpetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MagicCarpet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MagicCarpet-tvOS

end
